workflows:
  my-workflow:
    scripts:
      # Install dependencies
      - npm install
      # Install Netlify CLI
      - npm install -g netlify-cli
      # Build the website
      - npx expo export:web
      # Deploy to Netlify
      - netlify deploy --auth gUApKAogZF3Qtc-ibWV9sUA1ZGai7vv14NNNocIfSLc --site 25aabd83-c303-4697-af55-cffb8c4f4040 --prod --dir ./web-build
    artifacts:
      - web-build/index.html
      - web-build/static/**
      - web-build/asset-manifest.json
    publishing:
      email:
        recipients:
          - thanhdat9096@gmail.com
          - loichuanhuynh@gmail.com
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: develop
          include: false
      cancel_previous_builds: true
