workflows:
  # This workflow runs on every commit to the master branch
  my-workflow:
    environment:
      vars:
        NODE_OPTIONS: --openssl-legacy-provider
        API_Key: AIzaSyCsTsN2T8xfPUzV7-6RQNEHHcfxp2YdD6M
        GENERATE_SOURCEMAP: false
    scripts:
      # Install dependencies
      - npm install
      # Build the website
      - npx expo export:web
    artifacts:
      # Specify the files you want to save as artifacts here
      # For example:
      # - build/*
      - index.html
      - build/static/**
      - build/asset-manifest.json
    publishing:
      email:
        recipients:
          - thanhdat9096@gmail.com
          - loichuanhuynh@gmail.com
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: develop
          include: false
      cancel_previous_builds: true
