workflows:
  my-workflow:
    environment:
      groups:
        - webapp
    scripts:
      # Install dependencies
      - npm install
      # Install Netlify CLI
      - npm install -g netlify-cli
      # Build the website
      - npx expo export:web
      # Deploy to Netlify
      - netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $site_id --prod --dir ./web-build
    artifacts:
      - web-build/index.html
      - web-build/static/**
      - web-build/asset-manifest.json
    publishing:
      email:
        recipients:
          - thanhdat9096@gmail.com
          - loichuanhuynh@gmail.com
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: main-backup
          include: true
      cancel_previous_builds: true